#tomcat
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    #驼峰规则
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/manager/*.xml
    
#log
logging:
  level:
    com.clark: debug
