#tomcat
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
#修改默认动态代理true(默认)为CGLIB,false为JDK PROXY
  aop:
   proxy-target-class: false
#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    #驼峰规则
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/manager/*.xml
    
#log
logging:
  level:
    com.clark: debug
